
stages:
    - SayHello
    - deploy
    
test:
    stage: SayHello
    tags:
        - keys-self
    script:
        - printf "Hello! Today is %s\n" "$(date '+%A %B %d %r')"

postit:
  stage: deploy
  script:
     - eval $(ssh-agent -s)
#     - ssh-add -l
#    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
     - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
#     - rsync -auiv --delete -e "ssh" src/ 411orang@linux.cs.odu.edu:secure_html/
#     - rsync -auiv --delete -e "ssh -i ${HOME}/.ssh/Teamwebsite_deploy" src/ 411orang@linux.cs.odu.edu:.
     - rsync -auiv -e ssh src/ ekeys@linux.cs.odu.edu:.
  
  tags:
    - keys-self

  only:
    - master
