language: bash
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_c76ede9bdf8d_key -iv $encrypted_c76ede9bdf8d_iv
  -in secrets.tar.enc -out /tmp/secrets.tar -d
- tar -xf /tmp/secrets.tar -C /tmp
- cat /tmp/deploy-host.pub > $HOME/.ssh/known_hosts
- eval `ssh-agent -s`
- chmod 600 /tmp/do-amberreeve_rsa
- ssh-add /tmp/do-amberreeve_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
  - rsync -ruiv --delete-after -e ssh $TRAVIS_BUILD_DIR/src/ travisci@$DESTINATION_SERVER:/var/www/etkeys.net/
