
name: DEPLOY
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          cp src/robots.production.txt src/robots.txt
          rm src/robots.*.txt

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -ruiv --delete-after
          path: src/
          remote_path: /var/www/etkeys.xyz/
          remote_host: etkeys.xyz
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
            

