
name: DEPLOY (test)
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -ruiv --delete-after
          path: src/
          remote_path: /var/www/etkeys.xyz/
          remote_host: test.etkeys.xyz
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
            

