
name: DEPLOY (test)
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build with Hugo
        run: bash scripts/build.sh TEST

      - name: Copy appropriate robots.txt file
        run: cp src/robots.test.txt .publish/robots.txt

      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -ruiv --delete-after
          path: .publish/
          remote_path: /var/www/test.etkeys.me/
          remote_host: test.etkeys.me
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}
            

